spring:
    application:
        name: greeting_service
management: 
    endpoints:
        web:
            exposure:
                include:
                - '*'
greeting_service:
    greeting: "ello"
    default-value: "World"